### ISSUE TITLE
Duplicate BLSession -> BeamCalendar relationship?

### ISSUE THREAD

**Issue by rjgildea** [DiamondLightSource/ispyb-database#132]
There appears to be a duplicate relationship between BLSession -> BeamCalendar, is this correct?

https://github.com/DiamondLightSource/ispyb-database/blob/0ccd996220be28b7a39ee3e226f000e6cbc3901d/schemas/ispyb/tables.sql#L750-L753

The resulting SQLAlchemy ORM class has this relationship duplicated:

https://github.com/DiamondLightSource/ispyb-api/blob/c59197cf8352056148cc9d3aae85c4f176880d0d/src/ispyb/sqlalchemy/_auto_db_schema.py#L2394-L2401

which leads to the following error when using the models:
```
SAWarning: relationship 'BLSession.BeamCalendar1' will copy column BeamCalendar.beamCalendarId to column BLSession.beamCalendarId, which conflicts with relationship(s): 'BLSession.BeamCalendar' (copies BeamCalendar.beamCalendarId to BLSession.beamCalendarId). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="BeamCalendar"' to the 'BLSession.BeamCalendar1' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
```

**Comment by KarlLevik** [comment]
This is a bit strange as the update script should have dropped the old constraint:

https://github.com/DiamondLightSource/ispyb-database/blob/0ccd996220be28b7a39ee3e226f000e6cbc3901d/schemas/ispyb/updates/2022_04_12_BLSession_fk_beamCalendarId_set_null.sql#L3-L6

However, running the update script on a the old version of the table does not drop the constraint, and it also does not produce any warning or error message.

Anyway, a statement `ALTER TABLE BLSession DROP CONSTRAINT BLSession_ibfk_3;` does the job. I'll push a new update script to do that.

**Comment by rjgildea** [comment]
Fixed by https://github.com/DiamondLightSource/ispyb-database/commit/cb0a301d16fb2492091aab427fccdc6f16987e0d and
