### ISSUE TITLE
How to use data.sql file to test web

### ISSUE THREAD

**Issue by Baokangwen** [DiamondLightSource/ispyb-database#237]
@KarlLevik @Anthchirp @rjgildea @stufisher 
Hello everyone,
I uploaded the test data(data.sql) to the database and added the database configuration to the config.php file, but my frontend still can't display the data results, what additional configuration is needed?

**Comment by KarlLevik** [comment]
Hi @Baokangwen ,

The test data in `data.sql` is mostly for integration tests for projects such as [ispyb-api](https://github.com/DiamondLightSource/ispyb-api) and [gda-ispyb-api](https://github.com/DiamondLightSource/gda-ispyb-api). 

Are you trying to display this in SynchWeb? It should be possible to at least find the proposals and sessions a.k.a. visits from `data.sql` in SynchWeb, and maybe even display the data collections on these, although the raw and processed files that are referenced (e.g. in the `DataCollection` table) won't exist in your file system (or anywhere else), so SynchWeb will probably complain or crash. Still, maybe this is better than nothing? 

There are two proposals in that file: "cm14451" and "cm1". Assuming your user that is logged into SynchWeb either:

- belongs to a privileged group (see table `UserGroup_has_Person`, and find your user in the `Person` table), or  
- the user is a member of sessions on the above proposals (see table `Session_has_Person` and again find your user in the `Person` table)  

... then you should be able to find the proposals in SynchWeb by clicking on the proposals tab and entering the above mentioned proposal names (one at a time!).

We unfortunately do not have a proper, curated set of test data, which would consist of raw and processed files in a folder structure plus a `data.sql` file referencing those raw and processed files.   

I hope that helps a bit.

**Comment by Baokangwen** [comment]
@KarlLevik 
Thank you.
I've recently tried your method normally.
