### ISSUE TITLE
`build.sh` references files not in release

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/ispyb-database#91]
When running `build.sh` off a release archive I get the following warnings:
```
./build.sh: line 12: bin/functions.sh: No such file or directory
Dropping + creating build database
./build.sh: line 33: bin/missed_updates.sh: No such file or directory
```

**Comment by KarlLevik** [comment]
Have just made release [v1.23.1](https://github.com/DiamondLightSource/ispyb-database/releases/tag/v1.23.1) which contains the missing files.
